name: eslint test

on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: pranavyaligouda/crud-api
  

jobs:
  eslint-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install --include=dev

    - name: Run eslint test
      run: npm run lint
  
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout Repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Build Docker Image
    - name: Build Docker image
      run: |
        echo "Building Docker Image"]
        docker build -t ${{ env.IMAGE_NAME }}:test .
        echo "Docker image build successfully"
    
    # Test Docker Container
    - name: Test Docker Container
      run: |
        echo "Running docker container"
        docker run -d -p 8080:5000 --name test-app \
          -e NODE_ENV=production \
          -e PORT=5000 \
          -e MONGODB_URI="${{ secrets.MONGODB_URI }}" \
          -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
          ${{ env.IMAGE_NAME }}:test
        echo "Waiting for application startup"
        sleep 7

        echo "Health Check"
        if curl -f  http://localhost:8080/api/v1/health --max-time 10; then
          echo "Health check passed"
        else 
          echo "Health check failed"
          docker logs test-app
          exit 1
        fi

        echo "stopping and removing test container"
        docker stop test-app
        docker rm test-app
        echo "Test container stopped and removed"

    # Setup Docker Buildx
    - name: Set up Docker Buildx
      if: github.event_name != 'pull_request'
      uses: docker/setup-buildx-action@v3

    # Registry Authentication
    - name: Login to dockerhub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and Push Docker Image
    - name: Build and push docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64

    # Clean up test image
    - name: Clean up test image
      run: |
        echo "Removing test image"
        docker rmi ${{ env.IMAGE_NAME }}:test || true
        echo "Test image removed"